// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzhUqitS_UrN9N6G8-85I2UjrDFSCSo9I',
    appId: '1:680151749830:web:7676410143f952edd6b3c7',
    messagingSenderId: '680151749830',
    projectId: 'maccave-app',
    authDomain: 'maccave-app.firebaseapp.com',
    storageBucket: 'maccave-app.appspot.com',
    measurementId: 'G-SWX7EYKGW4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt_PneTe2svL2EseHy-rpYauv69j8wND4',
    appId: '1:680151749830:android:035c46493b3b0002d6b3c7',
    messagingSenderId: '680151749830',
    projectId: 'maccave-app',
    storageBucket: 'maccave-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQCk6OBy9zfQ6h72EEoL40bgGlDGJQE1w',
    appId: '1:680151749830:ios:3b5ff120d46bb595d6b3c7',
    messagingSenderId: '680151749830',
    projectId: 'maccave-app',
    storageBucket: 'maccave-app.appspot.com',
    androidClientId: '680151749830-6740fub5pl1c7mlvstaff0omil9l2qej.apps.googleusercontent.com',
    iosClientId: '680151749830-vtk605ctp2dnhqltuh8727omkr8s3d37.apps.googleusercontent.com',
    iosBundleId: 'com.jhcompany.maccave',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQCk6OBy9zfQ6h72EEoL40bgGlDGJQE1w',
    appId: '1:680151749830:ios:3b5ff120d46bb595d6b3c7',
    messagingSenderId: '680151749830',
    projectId: 'maccave-app',
    storageBucket: 'maccave-app.appspot.com',
    androidClientId: '680151749830-6740fub5pl1c7mlvstaff0omil9l2qej.apps.googleusercontent.com',
    iosClientId: '680151749830-vtk605ctp2dnhqltuh8727omkr8s3d37.apps.googleusercontent.com',
    iosBundleId: 'com.jhcompany.maccave',
  );
}
